#!/bin/bash
set -eufo pipefail
PROJECT_DIR="$(cd -- "$(dirname -- "$0")/.." && pwd)"
cd "$PROJECT_DIR"

readonly ESC=$'\033'"["
readonly BOLD="${ESC}1m"
readonly RESET="${ESC}0m"

git fetch
git checkout latest
git submodule update

scripts/build

echo -e "\n${BOLD}Stopping nevschat.$RESET"
monit stop nevschat
while true; do
    docker top nevschat > /dev/null 2>&1 || break
    sleep 1
done

sleep 5

echo -e "\n${BOLD}Starting nevschat.$RESET"
monit start nevschat
