#!/bin/bash
set -eufo pipefail
PROJECT_DIR="$(cd -- "$(dirname -- "$0")/.." && pwd)"
cd "$PROJECT_DIR"

readonly ESC=$'\033'"["
readonly BOLD="${ESC}1m"
readonly RESET="${ESC}0m"

echo -e "\n${BOLD}Building nevschat docker image.$RESET"
docker build -t nevschat:latest .
docker system prune --force

echo -e "\n${BOLD}Stopping nevschat.$RESET"
monit stop nevschat
while true; do
    docker top nevschat > /dev/null || break
    sleep 1
done

echo -e "\n${BOLD}Starting nevschat.$RESET"
monit start nevschat
