#!/bin/bash
set -eufo pipefail
PROJECT_DIR="$(cd -- "$(dirname -- "$0")/.." && pwd)"
cd "$PROJECT_DIR"

if micromamba env list | grep '\bnevschat\b'; then
	micromamba env remove -yn nevschat
fi
eval "$(micromamba shell hook --shell )"
micromamba create -yn nevschat python=3.12.3
micromamba install -yqn nevschat \
	--channel conda-forge \
	--channel defaults \
	--quiet \
	--yes \
	`# prod` \
	requests==2.31.0 \
	`# dev` \
	bandit \
	coverage \
	isort \
	mypy \
	pylint \
	pytest \
	pyupgrade \
	ruff \
	types-beautifulsoup4=4.12.0 \
	types-requests==2.31.0
micromamba run -n nevschat pip install -U \
	beautifulsoup4==4.12.3 \
	deepl==1.18.0 \
    jamdict==0.1a11.post2 \
    jamdict-data==1.5 \
	google-cloud-texttospeech==2.16.3 \
	openai==1.30.1
[ -d reflex ] ||
	git clone git@github.com:reflex-dev/reflex.git &&
	git submodule update
micromamba run -n nevschat pip install -e reflex
echo Done.
