#!/bin/bash
set -eufo pipefail
PROJECT_DIR="$(cd -- "$(dirname -- "$0")/.." && pwd)"
cd "$PROJECT_DIR"

# This is for working on contributions to Reflex.

# shellcheck source=/dev/null
. ~/miniconda3/etc/profile.d/conda.sh
conda deactivate
conda env remove -n reflex
conda create -yqn reflex python=3.11
conda activate reflex
conda install -yq \
	--channel conda-forge \
	--channel defaults \
	--quiet \
	--yes \
	`# prod` \
	pandas \
	urllib3 \
	`# dev` \
	bandit \
	black \
	coverage \
	isort \
	mypy \
	poetry \
	pylint \
	pyright \
	pytest \
	pytest-asyncio \
	pyupgrade
echo Done.
