#!/usr/bin/env bash
# For NixOS run in `nix-shell -p pkgs.python312`,
# with `programs.nix-ld.enable = true;`.
set -eufo pipefail
PROJECT_DIR="$(cd -- "$(dirname -- "$0")/.." && pwd)"
cd "$PROJECT_DIR"

GREEN="\e[32m"
RESET="\e[0m"

if [[ $# -ne 1 ]] || {
    [[ "$1" != 'dev' ]] &&
    [[ "$1" != 'prod' ]];
}; then
    echo "USAGE: install <dev|prod>"
    exit 1
fi

env="$1"

if micromamba env list | grep '\bnevschat\b'; then
	micromamba env remove \
	--name nevschat \
	--yes
fi

echo -e "${GREEN}\nCreating environment.${RESET}"
micromamba create \
	--channel conda-forge \
	--channel defaults \
	--name nevschat \
	--yes \
	python=3.12.3

echo -e "${GREEN}\nInstalling dependencies from conda-forge.${RESET}"
micromamba install \
	--channel conda-forge \
	--channel defaults \
	--name nevschat \
	--yes \
	beautifulsoup4==4.12.3 \
	requests==2.32.3 \

if [[ "$env" == "dev" ]]; then
    echo -e "${GREEN}\nInstalling dev dependencies from conda-forge.${RESET}"
    micromamba install \
    	--channel conda-forge \
    	--channel defaults \
    	--name nevschat \
    	--yes \
    	bandit \
    	coverage \
    	isort \
    	mypy \
    	pylint \
    	pytest \
    	pyupgrade \
    	ruff \
    	types-beautifulsoup4=4.12.0 \
    	types-requests==2.31.0
fi

echo -e "${GREEN}\nInstalling dependencies with pip.${RESET}"
micromamba run \
	--name nevschat \
	pip install \
    	deepl==1.20.0 \
    	jamdict==0.1a11.post2 \
    	jamdict-data==1.5 \
    	google-cloud-texttospeech==2.21.1 \
    	openai==1.57.1

if [[ "$env" == "prod" ]]; then
	micromamba run \
		--name nevschat \
		pip install \
	        reflex==0.7.0
else
    [ -d reflex ] ||
		echo -e "${GREEN}\nCloning reflex.\e[0m" &&
		git clone git@github.com:reflex-dev/reflex.git &&
		git submodule update

    echo -e "${GREEN}\nInstalling reflex as editable.${RESET}"
    micromamba run \
		--name nevschat \
	    pip install \
	        --editable \
	        reflex
fi

echo -e "${GREEN}\nDone.${RESET}"
