#!/bin/bash
set -eufo pipefail
PROJECT_DIR="$(cd -- "$(dirname -- "$0")/.." && pwd)"
cd "$PROJECT_DIR"

# shellcheck source=/dev/null
. ~/miniconda3/etc/profile.d/conda.sh
conda config --set auto_activate_base false
conda deactivate
conda env remove -n nevschat
conda create -yqn nevschat python=3.12
conda activate nevschat
conda install -yq \
	--channel conda-forge \
	--channel defaults \
	--quiet \
	--yes \
	`# prod` \
	`# dev` \
	bandit \
	black \
	coverage \
	isort \
	mypy \
	pylint \
	pytest \
	pyupgrade
pip install -U \
	openai==1.3.4
[ ! -d reflex ] || git clone git@github.com:reflex-dev/reflex.git
pip install -e reflex
echo Done.
