#!/usr/bin/env bash
set -euo pipefail
shopt -s globstar
PROJECT_DIR="$(cd -- "$(dirname -- "$0")/.." && pwd)"
cd "$PROJECT_DIR"

mypy --strict app
ruff check --fix --exclude=.web app
bandit --recursive --skip B101 --exclude=.web --quiet app
PYVERSION=py312
pyupgrade --$PYVERSION-plus -- app/**/*.py
isort --force-single-line-imports --profile black -- app/**/*.py
ruff format --target-version=$PYVERSION -- app/**/*.py
git diff --exit-code '*.py'

echo 'Lint is happy.'
