#!/bin/bash
set -euo pipefail
shopt -s globstar
PROJECT_DIR="$(cd -- "$(dirname -- "$0")/.." && pwd)"
cd "$PROJECT_DIR"

mypy --strict app
pylint --recursive=y --ignore=.web app
bandit --recursive --skip B101 --exclude=.web --quiet app
PYVERSION=py39
pyupgrade --$PYVERSION-plus -- app/**/*.py
isort --force-single-line-imports --profile black -- app/**/*.py
black --target-version=$PYVERSION -- app/**/*.py
git diff --exit-code '*.py'

echo 'Lint is happy.'
