#!/bin/bash
set -eufo pipefail
PROJECT_DIR="$(cd -- "$(dirname -- "$0")/.." && pwd)"
cd "$PROJECT_DIR"

readonly ESC=$'\033'"["
readonly BOLD="${ESC}1m"
readonly RESET="${ESC}0m"

echo -e "\n${BOLD}Building nevschat docker image.$RESET"
scripts/build

echo -e "\n${BOLD}Starting nevschat in dev mode.$RESET"
docker run \
    --rm \
    --publish 3000:3000 \
    --publish 8000:8000 \
    --name nevschat \
    nevschat:latest
